apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bitnami-tomcat9-debian-10-r13
  name: bitnami-tomcat9-debian-10-r13
spec:
  volumes:
    - name: bitnami-tomcat-storage
      persistentVolumeClaim:
        claimName: bitnami-tomcat-claim  
    - name: tomcat-conf-volume
      configMap:
        name: tomcat-conf-cm     
  containers:
    - name: bitnami-tomcat9-debian-10-r13
      image: docker.io/bitnami/tomcat:9.0.34-debian-10-r13
      imagePullPolicy: IfNotPresent
      env:
        - name: JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addressess=true -Dfile.encoding=UTF-8 -Djava.awt.headless=true -XX:+UseG1GC -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=90.0"
        - name: TOMCAT_USERNAME
          value: "admin"
        - name: TOMCAT_PASSWORD
          value: "admin"  
        - name: TOMCAT_ALLOW_REMOTE_MANAGEMENT
          value: "1"
      readinessProbe:
        tcpSocket:
          port: http-8080
        initialDelaySeconds: 5
        timeoutSeconds: 20
        periodSeconds: 5
      livenessProbe:
        tcpSocket:
          port: http-8080
        initialDelaySeconds: 10
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 1
        successThreshold: 1
      ports:   
      - name: http-8080
        containerPort: 8080
      resources:
        requests:
          memory: "256Mi"
          cpu: "550m"
        limits:
          memory: "256Mi"
          cpu: "750m"
      volumeMounts:
        - name: bitnami-tomcat-storage
          mountPath: "/bitnami-tomcat-storage"
        - name: tomcat-conf-volume
          mountPath: /cm/conf
      lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /cm/conf/* /opt/bitnami/tomcat/conf"]    
 