apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tomcat-bitnami-original
  name: tomcat-bitnami-original
spec:  
  containers:
    - name: tomcat-bitnami-original
      # image: docker.io/bitnami/tomcat:9.0-debian-10
      image: docker.io/andriykalashnykov/bitnami-tomcat9-jdk18:1.0
      imagePullPolicy: Always
      env:
        - name: JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addressess=true -Dfile.encoding=UTF-8 -Djava.awt.headless=true -XX:+UseG1GC -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=90.0"
        - name: TOMCAT_USERNAME
          value: "admin"
        - name: TOMCAT_PASSWORD
          value: "admin"
        - name : TOMCAT_AJP_PORT_NUMBER
          value: "8019"    
        - name: TOMCAT_ALLOW_REMOTE_MANAGEMENT
          value: "1"
        - name: TOMCAT_ALLOW_REMOTE_MANAGEMENT_ANY_IP
          value: "1"  
      readinessProbe:
        tcpSocket:
          port: http-8080
        initialDelaySeconds: 5
        timeoutSeconds: 20
        periodSeconds: 5
      livenessProbe:
        tcpSocket:
          port: http-8080
        initialDelaySeconds: 10
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 1
        successThreshold: 1
      ports:   
      - name: http-8080
        containerPort: 8080
      resources:
        requests:
          memory: "256Mi"
          cpu: "550m"
        limits:
          memory: "256Mi"
          cpu: "750m"
 